# Generated by Django 5.0.1 on 2024-04-19 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0003_alter_customers_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='customers',
            name='city',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='customers',
            name='locality',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
