# Generated by Django 5.0.1 on 2024-04-19 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0004_customers_city_customers_locality'),
    ]

    operations = [
        migrations.AddField(
            model_name='customers',
            name='pincode',
            field=models.CharField(max_length=10, null=True),
        ),
    ]
